services:

  apache:
    container_name: convenia-site
    build: ./docker/.
    volumes:
      - .:/var/www/html/convenia
    restart: always
    ports:
      - ${APP_PORT}:80
    networks:
      - convenia-network
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
    networks:
      - convenia-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - convenia-network

networks:
  convenia-network: {}
